<script type="text/javascript">
  $(document).ready(function () {
    $.each($(".form"), function (index, value) {
      var form_height = parseInt($(value).actual("outerHeight", {
        includeMargin: true
      }));
      $(value).parents(".form_wrapper").height(form_height + 120);
      $(value).parents(".form_box").height(form_height + 120 - 20);
    });
    $("#payu_submit").on("click", function (event) {
      validate_ajax.url = "/admin/validator/validateform";
      validate_ajax.validate($(this));
      if ($(".errors_tip").length) {
        event.preventDefault();
        event.stopPropagation();
      }
      $("form").submit();
    }).css({
      "cursor": "pointer"
    });
    $("#amount").val(roundnumber($("#amount").val()) + " PLN");
  });
</script>
<?php
$aErrors = array();
foreach ($this->element as $oElement) {
  if (!in_array($oElement->getName(), array("seo_group", "chat_close_group", "journal_group", "not_valid"))) {
    $aError = $oElement->getMessages();
    if (is_array($aError) && count($aError) > 0) {
      foreach ($aError as $sErrorText) {
        $aErrors[] = "<p id=\"{$oElement->getName()}-error_text\"><strong>{$oElement->getLabel()}</strong><i>$sErrorText</i></p>";
      }
      $oElement->setAttrib("class", "field_error");
    }
  }
}
?>
<div class="form_wrapper">
  <div class="form_box">
    <form class="form" action="<?php echo $this->element->getAction(); ?>"
          method="<?php echo $this->element->getMethod(); ?>">
      <?php foreach ($this->element as $oElement): ?>
        <?php if (!in_array($oElement->getName(), array("submit"))): ?>
          <?php if ($oElement->getType() == "Zend_Form_Element_Hidden" || $oElement->getType() == "Zend_Form_Element_Hash"): ?>
            <?php echo $oElement; ?>
          <?php else: ?>
            <dl><?php echo $oElement; ?></dl>
          <?php endif; ?>
        <?php else: ?>
          <dl>
            <dt><label>Wybierz formę płatności:</label></dt>
            <dd>
              <!--              <yp:paymentButton merchant_id="-->
              <?php //echo $this->element->getMerchantId(); ?><!--" amount="-->
              <?php //echo $this->element->getAmount(); ?><!--" descr="-->
              <?php //echo $this->element->getDescr(); ?><!--" order_id="" product_id="" user_id="-->
              <?php //echo $this->element->getUserId(); ?><!--" time="-->
              <?php //echo $this->element->getTime(); ?><!--" hash="-->
              <?php //echo $this->element->getHash(); ?><!--"-->
              <!--                                product_img="http://zk.horizon2.pro-linuxpl.com/skins/user/gfx/preview_pdf.png"></yp:paymentButton>-->
              <a id="payu_submit"><img alt="Konto PayU - Jedno konto do zakupów"
                                       src="http://static.payu.com/pl/standard/partners/buttons/payu_account_button_01.png"/></a>
            </dd>
          </dl>
        <?php endif; ?>
      <?php endforeach; ?>
    </form>
    <div id="legend">
      <span id="req" class="pos_left"></span>
      <span class="pos_left"><?php echo $this->translate("Pole obowiązkowe"); ?></span>
    </div>
  </div>
</div>
<div class="clear"></div>
