<script type="text/javascript">
  $(document).ready(function () {
    $.each($(".form"), function (index, value) {
      var form_height = parseInt($(value).actual("outerHeight", {
        includeMargin: true
      }));
      $(value).parents(".form_wrapper").height(form_height + 80);
      $(value).parents(".form_box").height(form_height + 80 - 20);
    });
    $.each($(".strong"), function (index, value) {
      var name = $(value).attr("class").split(" ")[0];
      $("." + name).on("click",function () {
        $("#" + name + "_wrapper").toggle();
        if ($("#" + name + "_wrapper").is(":hidden"))
          $(this).find(".yellow").html(translator.get("btn_pokaz_view"));
        else
          $(this).find(".yellow").html(translator.get("btn_ukryj_view"));
      }).css({
        "cursor": "pointer"
      });
    });
    $("input[id*=submit][type=submit]").unbind("click").bind("click", function (event) {
      validate_ajax.url = "/admin/validator/validateform";
      validate_ajax.validate($(this));
      if ($(".errors_tip").length) {
        event.preventDefault();
        event.stopPropagation();
      }
    });
  });
</script>
<?php
$aErrors = array();
foreach ($this->element as $oElement) {
  if (!in_array($oElement->getName(), array("seo_group", "chat_close_group"))) {
    $aError = $oElement->getMessages();
    if (is_array($aError) && count($aError) > 0) {
      foreach ($aError as $sErrorText) {
        $aErrors[] = "<p id=\"{$oElement->getName()}-error_text\"><strong>{$oElement->getLabel()}</strong><i>$sErrorText</i></p>";
      }
      $oElement->setAttrib("class", "field_error");
    }
  }
}
?>
<div class="form_wrapper">
  <div class="form_box">
    <form class="form" action="<?php echo $this->element->getAction(); ?>" method="<?php echo $this->element->getMethod(); ?>">
      <?php foreach ($this->element as $oElement): ?>
        <?php if (!in_array($oElement->getName(), array("seo_group", "chat_close_group", "journal_group", "not_valid"))): ?>
          <?php if ($oElement->getType() == "Zend_Form_Element_Hidden" || $oElement->getType() == "Zend_Form_Element_Hash"): ?>
            <?php echo $oElement; ?>
          <?php else: ?>
            <dl><?php echo $oElement; ?></dl>
          <?php endif; ?>
        <?php else: ?>
          <dl><?php echo $oElement; ?></dl>
        <?php endif; ?>
      <?php endforeach; ?>
    </form>
    <div id="legend">
      <span id="req" class="pos_left"></span>
      <span class="pos_left"><?php echo $this->translate("Pole obowiązkowe"); ?></span>
    </div>
  </div>
</div>
<div class="clear"></div>
