<div>
  <img class="pos_left" src="<?php echo $this->baseUrl() . '/skins/default/gfx/error.png' ?>"/>
  <a class="pos_left" class="click" href="<?php echo $this->baseUrl(); ?>"/>

  <div class="text"><p>Wystąpił błąd. Spróbuj ponownie.</p></div>
  </a>
</div>
<div class="clear"></div><br/>

<h1>An error occurred</h1>
<h2><?php echo $this->message ?></h2>

<?php if (isset($this->exception)): ?>
  <h3>Exception information:</h3>
  <p>
    <b>Message:</b> <?php echo $this->exception->getMessage() ?>
  </p>

  <h3>Stack trace:</h3>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo var_export($this->request->getParams(), true) ?>
  </pre>
<?php endif; ?>
