<?php echo $this->doctype(); ?>
<html>
<head>
  <?php echo $this->loadSkin("admin"); ?>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headScript(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->googleAnalytics(); ?>
</head>
<body>
<div id="container">
  <?php echo $this->loadDebug(); ?>
  <header>
    <div id="user_box">
      <?php echo $this->userInfo(); ?>
    </div>
  </header>
  <nav id="menu">
    <?php echo $this->loadMenu("topnav"); ?>
  </nav>
  <section id="breadcrumbs">
    <?php echo $this->loadBreadcrumbs(); ?>
  </section>
  <section id="left_menu">
    <?php echo $this->loadSubMenu(1, "subnav"); ?>
  </section>
  <section id="content">
    <?php echo $this->layout()->content ?>
  </section>
  <footer></footer>
</div>
</body>
</html>
