<?php echo $this->doctype(); ?>
<html>
<head>
  <?php echo $this->loadSkin("borrower"); ?>
  <?php echo $this->headMeta(); ?>
  <?php echo $this->headTitle(); ?>
  <?php echo $this->headScript(); ?>
  <?php echo $this->headLink(); ?>
  <?php echo $this->googleAnalytics(); ?>
</head>
<body>
<div id="container">
  <header>
    <div id="user_box">
      <?php echo $this->userInfo(); ?>
    </div>
    <div id="header_baner"></div>
  </header>
  <section id="content_login_index">
    <?php echo $this->layout()->content ?>
  </section>
  <footer>
    <p style="float:right;">Serwis zdalnego zamawiania kopii z materiałów bibliotecznych <a href="http://bg.pw.edu.pl" target="_blank">Biblioteki Głównej Politechniki Warszawskiej</a></p>

    <p style="float:left;"><a class="statute" href="http://demokopiealeph.libcom.pl/regulamin.pdf" target="_blank">Regulamin usługi</a></p>
  </footer>
</div>
</body>
</html>
